[project]
name = "simple_guardrail"
version = "0.0.0"
description = "simple_guardrail usage example"
requires-python = ">=3.11,<3.14"
readme = "README.md"
dependencies = [
    "gllm-guardrail>=0.6.0,<0.7.0",
]

[[tool.uv.index]]
name = "gen-ai-internal"
url = "https://glsdk.gdplabs.id/gen-ai-internal/simple/"

[tool.uv.sources]
gllm-guardrail = { index = "gen-ai-internal" }
