[project]
name = "query-transformer"
version = "0.0.0"
description = "Query Transformer usage example"
requires-python = ">=3.11,<3.14"
readme = "README.md"
dependencies = [
    "gllm-retrieval>=0.6.8,<0.7.0",
    "gllm-inference[openai]>=0.6.0,<0.7.0",
    "python-dotenv>=1.0.0,<2.0.0",
]

[[tool.uv.index]]
name = "gen-ai-internal"
url = "https://glsdk.gdplabs.id/gen-ai-internal/simple/"

[tool.uv.sources]
gllm-retrieval = { index = "gen-ai-internal" }
gllm-inference = { index = "gen-ai-internal" }
