[project]
name = "web_search"
version = "0.0.0"
description = "web_search usage example"
requires-python = ">=3.11,<3.14"
readme = "README.md"
dependencies = [
    "gllm-inference>=0.6.115,<0.7.0",
]

[[tool.uv.index]]
name = "gen-ai-internal"
url = "https://glsdk.gdplabs.id/gen-ai-internal/simple/"

[tool.uv.sources]
gllm-inference = { index = "gen-ai-internal" }
